Fix windows builds failing to link
nukeykt/Nuked-SC55 pull request #69
Opened 2024-05-02 20:47 UTC by nikitalita

If WIN32_CONSOLE is not defined, the exe will fail to link:

```
[build] MSVCRT.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) [F:\workspace\Nuked-SC55\build\nuked-sc55.vcxproj]
```

Defining WIN32_CONSOLE in the CFLAGS fixes the issue

2024-05-02 21:35 UTC, Kappa971 commented
This should finally close this issue: https://github.com/nukeykt/Nuked-SC55/issues/16

2024-05-03 01:08 UTC, Wohlstand requested changes
Seems good, but this could be better:

Please add the:
```cmake
if(MSVC)
    target_compile_definitions(nuked-sc55 PRIVATE "-DWIN32_CONSOLE")
endif()
```

after these lines:
```cmake
add_executable(nuked-sc55 ${SC55_SRC} ${UTF8MAIN_SRCS})
set_nopie(nuked-sc55)
```
and that will be enough.

2024-05-03 01:08 UTC, Wohlstand commented on CMakeLists.txt
> +    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DWIN32_CONSOLE")
You don't need these once you already set the CMAKE_C_FLAGS / CMAKE_CXX_FLAGS, content of these variables will be included in all builds.

2024-05-03 01:08 UTC, Wohlstand commented on CMakeLists.txt
> +if (WIN32)
This is problem of MSVC exclusive and this doesn't happen on MinGW builds at all. So, you can freely use the `MSVC` variable here.

2024-05-04 01:44 UTC, nikitalita commented
ok, done

2024-05-04 05:28 UTC, Wohlstand approved these changes
Now all is fine!

2024-05-04 05:29 UTC, merged